### ISSUE TITLE
style?  gem5 not cap at beginning of sentence

### ISSUE THREAD

**Issue by michaeldupton** [darchr/gem5-20-paper#12]
when gem5 is the first word of a sentence, it is still not capitalized.

maybe replace with 'The gem5 simulator' ?

or maybe I am too pedantic.

**Comment by powerjg** [comment]
gem5 should never be capitalized. I'll probably go back and make sure that it's not the first word in a sentence anywhere. 

On the other hand, how do you feel about starting a sentence with iPhone? For example...

iPhones are very proprietary.

(Leaving this open so I don't forget to go back through and do this :).

**Comment by cento** [comment]
The #16 goes in that direction: "The gem5 simulator" when possible, and "gem5"  within the sentence.
