### ISSUE TITLE
Minor improvements in section 2.6.1 (changes/ruby-cache-model.tex)

### ISSUE THREAD

**Issue by tommarin** [darchr/gem5-20-paper#14]
> At level 0, the protocol has separate caches for instruction and data.

Shouldn't it be _instructions_ instead? The singular is OK when using the expression _instruction cache_, but in this case the plural is probably more correct.

> The first and the second levels do not distinguish between instruction and data.

Same as before.

> Levels 0 and 1 are private to the CPU core, **which** the second level is shared across (possibly a subset) cores

Was the word _which_ mistakenly used instead of _while_?

By the way, to make it easier to read I would maybe merge the second sentence with the first one. I would also move the expression _possibly a subset_ at the end of the third sentence, like:

> Levels 0 and 1 are private to each CPU core while the second level is shared across cores, all of them or possibly a subset.

**Comment by powerjg** [comment]
closed by #40
