### ISSUE TITLE
Integration of RISC-V test suite in gem5

### ISSUE THREAD

**Issue by qtt2** [darchr/gem5-20-paper#25]
Back when I submitted patches to integrate RISC-V test suite into gem5, it only supported syscall emulation. Not sure if that has changed since then, but as far as I know FS for RISC-V is not yet supported? If that's correct, I would like the sentence about RISC-V test suite to be moved into section 2.8.1 (general RISC-V ISA implementation).

**Comment by powerjg** [comment]
Great point!
