### ISSUE TITLE
Sec 2.6.1: New 3 Level Ruby Protocol?

### ISSUE THREAD

**Issue by seanzw** [darchr/gem5-20-paper#29]
The description about the new 3-level ruby protocol seems vague to me. Is this the MESI_THREE_LEVEL protocol?

**Comment by aakahlow** [comment]
It must be MESI_Three_Level as that's the only protocol with L0 cache

**Comment by aakahlow** [comment]
created PR # 42 for this

**Comment by powerjg** [comment]
closed by #42
