### ISSUE TITLE
Page 4 Line 8: Any ISAs can be used with any CPUs

### ISSUE THREAD

**Issue by seanzw** [darchr/gem5-20-paper#31]
This may be minor thing, but by default x86 does not enable MinorCPU, but the user can modify the building script to enable that, but last time I tried this there are still some problems of branch prediction in MinorCPU when using x86. But overall I feel it is reasonable to say any ISA can be used with any CPUs.

**Comment by aakahlow** [comment]
I agree with the x86 MinorCPU bug and that it is missing from the default build options. But, I think the statement "Any ISAs can be used with any CPUs" is still fundamentally correct.

**Comment by powerjg** [comment]
Thanks for the feedback, Zhengrong. Personally, i would consider the MinorCPU not fully supporting x86 a bug. If you have details on what's wrong, we'd appreciate it if you created a jira issue with some of the details, and we can try to dig into it.
