### ISSUE TITLE
Sec 2.14.3 QoS a little bit abstract?

### ISSUE THREAD

**Issue by seanzw** [darchr/gem5-20-paper#32]
I feel this section is a little abstract and not that closely related to gem5. It would be great if it can cover more about the implementation in gem5 and what new research questions it empowers gem5 to explore?

**Comment by giactra** [comment]
Hi,
If you check the original draft we sent to Jason, there is a gem5 part which hasn't been added to the paper as far as I can see:

https://docs.google.com/document/d/1GRrNeFXO2IqimuxYmkODkLxssWb6-oUcXVvj8VbCoB8/edit#heading=h.iq0papa79ac

"My contribution involved the definition of a QoS-aware memory controller in gem5, and the definition of basic (example) policies modelling the prioritization algorithm of the memory controller. Those are the Fixed priority policy (every master in the system has a fixed priority assigned) and the Proportional Fair policy (where the priority of a master is dynamically adjusted at runtime based on utilization).
I have rewritten the DRAM controller in gem5 to include the QoS changes; with the framework in place a user can write its own policy and seamlessly plug it into a real memory controller model to unlock system wide explorations under its own arbitration algorithm."

**Comment by seanzw** [comment]
Thanks! I think including this in the maker will make it more complete.

**Comment by giactra** [comment]
The PR has been merged, feel free to close the issue

**Comment by powerjg** [comment]
Thanks everyone!
