### ISSUE TITLE
Move future to the end of the paper

### ISSUE THREAD

**Issue by timothymjones** [darchr/gem5-20-paper#37]
To me the paper ends somewhat abruptly.  It might be the lack of a conclusions section, but I also wonder whether it would be better to talk about the future of gem5 at the end, after describing all the current features of the tool.  That way I feel there will be more of a narrative - you've told me about all the great things to do with gem5 now, what's happening next?

**Comment by powerjg** [comment]
Agreed. I need to do something about the abrupt ending. However, I want to have future toward the front with the assumption that people won't read beyond the first section :).

Closing now. I'm going to work on the ending. If after I make that change you still feel that it needs to be updated, feel free to reopen :).
