### ISSUE TITLE
Section 2.14.3 Quality of Service Extensions

### ISSUE THREAD

**Issue by hanhwi** [darchr/gem5-20-paper#41]
This subsection seems to describe the general definition of QoS and does not deal with what gem5 provides on QoS extensions.
I think this section needs to explain what and how gem5 provides QoS extensions.

**Comment by giactra** [comment]
There is already a pending issue about that:

https://github.com/darchr/gem5-20-paper/issues/32

I will create a PR today

**Comment by giactra** [comment]
https://github.com/darchr/gem5-20-paper/pull/50 has been merged. Feel free to close the issue
