### ISSUE TITLE
Comments about Fig1 and Section 1/1.1

### ISSUE THREAD

**Issue by hyoon838** [darchr/gem5-20-paper#46]
1. Can we show the citation distribution of gem5 paper over time in Figure 1? I am wondering the trend. Showing this may be helpful to stress the acceleration described in the section.

2. Page 3  - Line 5.
I think the flow from the first paragraph to the second paragraph is not that smooth. I am not sure what "these problems" mean.

3. Page 2 - Line 16
Gem5 -> The Gem5 community?

**Comment by powerjg** [comment]
1. Working on it :)
2. Fixed :).
3. Not sure where this is anymore :). Could you give more context?

**Comment by hyoon838** [comment]
I was referring to a paragraph below in Section 1. Please check the bold one.

The gem5 community strives to balance the needs of its three categories of users: academic researchers, industry researchers, and students. **For instance, gem5 strives to balance** adding new features (important to researchers) and astable code base (important for students).
