### ISSUE TITLE
SystemC integration described in section 1.2

### ISSUE THREAD

**Issue by kugwa** [darchr/gem5-20-paper#47]
"The IEEE standard SystemC API has also been integrated with gem5 to enable users with SystemC models to use them as gem5 components."

This description seems more like "SystemC within gem5" rather than "gem5 within SystemC" to me. However, I have heard that the SystemC implementation in gem5 is not designed to be completely compatible with the standard SystemC implementation, which means that one cannot run prebuilt SystemC modules as gem5 components directly.

**Comment by powerjg** [comment]
Yes, we have systemc within gem5 now :). See https://github.com/darchr/gem5-20-paper/commit/70485078aeaab58a901adc60c71bad548d434572
