### ISSUE TITLE
Suggestion: the overview section for describing major improvement

### ISSUE THREAD

**Issue by hanhwi** [darchr/gem5-20-paper#48]
Currently, the paper lists major improvements of gem5 in Section 2.
I like recently added Figure 2, which describes the overview of gem5. 
Could we provide a similar one for Section 2? 
Why don't we start the section with a table or some paragraphs that summarize the major improvements? That would be helpful for readers to get what advances in gem5 are in a glance.

**Comment by powerjg** [comment]
Good idea! I'll leave this open in the hopes that I can get to it :)

**Comment by powerjg** [comment]
See #89. I added a table which gives an overview of the major changes and points to each subsection. Thanks for the suggestion!
