### ISSUE TITLE
commit 7e4f832 erroneously removed the branch predictor section

### ISSUE THREAD

**Issue by Dibakar** [darchr/gem5-20-paper#69]
Hi Jason,

Just noticed that this commit (https://github.com/darchr/gem5-20-paper/commit/7e4f83267ea17de3e77637056e4a07af51570483#diff-41cd4cabd0f3cb6d6f90a3fdd6ba55f1) around "Update order, etc. Remove empty sections" in "changes/predictor-improvements.tex"  has erroneously removed the branch predictor section from the final draft. Looks like you might have erroneously commented out the inclusion of \input{changes/predictor-improvements}.

Please take a look into that. Thanks.

**Comment by powerjg** [comment]
Ha! Sorry about that! It's been a long week. I'll fix that.
