### ISSUE TITLE
Suggestion: Table with list of subsection in Section 2

### ISSUE THREAD

**Issue by aarmejach** [darchr/gem5-20-paper#89]
Section 2 has a lot of material, which is great. 

However, to get a quick grasp of all the new features/improvements it might be worth considering adding a table at the beginning of section 2 with the list of subsections. If the table is split in 2 columns it would take about 10 lines. 

The table can serve multiple purposes.
- Could be used to introduce the section with a bit more context
- Can help the reader navigate the paper
- Could be used to include additional content that refers to each subsection

Just a suggestion.

**Comment by powerjg** [comment]
I like this suggestion! Great idea!

**Comment by powerjg** [comment]
Done! Thanks for the suggestion :)
