### ISSUE TITLE
Add trademark symbols when referring to Arm technology

### ISSUE THREAD

**Issue by giactra** [darchr/gem5-20-paper#91]
The following is a comprehensive list:

https://www.arm.com/company/policies/trademarks/arm-trademark-list

As far as I can see from a first look we should be adding trademark symbols for the first occurrence of

- Arm
- TrustZone

**Comment by powerjg** [comment]
Could you create a PR, or would it be better if I did it?

**Comment by giactra** [comment]
I can do that Jason! I was busy and I wanted to flag this ASAP before the paper is published so that I have more time to do a thorough trademark check

**Comment by powerjg** [comment]
Sound good! Thanks!

I was planning to send this to AMD to have them add their sections today or tomorrow. As far as I can tell, they aren't going to be able to merge any changes while it's under review there. So, we need to be done before we send it to them.

**Comment by giactra** [comment]
https://github.com/darchr/gem5-20-paper/pull/93
