### ISSUE TITLE
Fix SVE contributors

### ISSUE THREAD

**Issue by giactra** [darchr/gem5-20-paper#98]
The list of contributors for the SVE improvement is (in alphabetical order)

Gabor Dozsa
Giacomo Gabrielli
Rekai Gonzalez-Alberquilla
Nathanael Premillieu
Javier Setoain

I  have been included in the author list for SVE (together with Giacomo Gabrielli and Javier Setoain) though I haven't really contributed a lot to that specific feature. I think I should be excluded from that paragraph and the people mentioned above should be added instead

**Comment by powerjg** [comment]
Also: Giacomo Gabrielli should be part of the author list.

**Comment by powerjg** [comment]
Just to double check, this was fixed by #100, right?

**Comment by giactra** [comment]
Yes #100 fixed it
